### ISSUE TITLE
Returning a subject?

### ISSUE THREAD

**Issue by MarcusRiemer** [pauldraper/neo-observable-input#2]
I have a scenario where a `@Input()` field could previously change via either the host component or an assignment in the component itself. I am not entirely sure that this is good design, but for the moment this is where I am at. Would you be willing to accept a PR that introduces a `subject` method along the lines of this?

```
  subject<T>(
    value: () => T,
    makeSubject: () => Subject<T> = () => new ReplaySubject<T>(1)
  ): Subject<T> {
    const subject = makeSubject();
    this._inputs.push(new ObservableInput(subject, value));
    return subject;
  }
```

**Comment by pauldraper** [comment]
Yes.

Though a workaround right now is

```ts
color: string;
colorSubject = new ReplaySubject(1);
color$ = merge(colorSubject, this.inputs.observe(() => this.color));
```

**Comment by MarcusRiemer** [comment]
The more I think about it, the more I prefer your design: It leaves the possibility to clearly define precedence.
